version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: example

  trello:
    build: .
    links:
      - db
    ports:
      - "0.0.0.0:3000:3000"
